import * as XLSX from "xlsx";
import type { ReportContext } from "@/modules/reports/core/report-context";

export interface ExcelColumn {
  header: string;
  accessor: (row: Record<string, unknown>) => unknown;
  width?: number;
}

function normalizeCellValue(value: unknown): string | number | boolean {
  if (value === null || value === undefined) return "";
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return value;
  }
  return String(value);
}

export interface ExcelDataSheet {
  name: string;
  columns: ExcelColumn[];
  rows: Record<string, unknown>[];
  totals?: Record<string, string | number>;
}

export interface ExcelWorkbookInput {
  title: string;
  context?: ReportContext;
  sheets: ExcelDataSheet[];
  fileName: string;
}

function cellWidth(value: string | number): number {
  const len = String(value).length;
  return Math.min(Math.max(len + 2, 10), 48);
}

export function autoFitColumns(sheet: XLSX.WorkSheet, colCount: number): void {
  const cols: XLSX.ColInfo[] = [];
  for (let c = 0; c < colCount; c++) {
    let max = 10;
    const range = XLSX.utils.decode_range(sheet["!ref"] ?? "A1");
    for (let r = range.s.r; r <= range.e.r; r++) {
      const cell = sheet[XLSX.utils.encode_cell({ r, c })];
      if (cell?.v !== undefined) {
        max = Math.max(max, cellWidth(cell.v as string | number));
      }
    }
    cols.push({ wch: max });
  }
  sheet["!cols"] = cols;
}

export function buildMetadataSheet(context: ReportContext, title: string): XLSX.WorkSheet {
  const rows = [
    ["CafeFlow Report"],
    ["Title", title],
    ["Organization", context.orgName],
    ["Store", context.storeName ?? "All"],
    ["Currency", context.currency],
    ["Generated by", context.generatedBy],
    ["Generated at", context.generatedAt],
    ["Filters", context.filterSummary],
  ];
  const sheet = XLSX.utils.aoa_to_sheet(rows);
  autoFitColumns(sheet, 2);
  return sheet;
}

function rowsToSheet(columns: ExcelColumn[], rows: Record<string, unknown>[]): XLSX.WorkSheet {
  const headers = columns.map((c) => c.header);
  const data = rows.map((row) =>
    columns.map((col) => normalizeCellValue(col.accessor(row)))
  );
  const sheet = XLSX.utils.aoa_to_sheet([headers, ...data]);
  if (columns.some((c) => c.width)) {
    sheet["!cols"] = columns.map((c) => ({ wch: c.width ?? 18 }));
  } else {
    autoFitColumns(sheet, columns.length);
  }
  return sheet;
}

export function appendTotalsRow(
  sheet: XLSX.WorkSheet,
  columns: ExcelColumn[],
  totals: Record<string, string | number>
): void {
  const range = XLSX.utils.decode_range(sheet["!ref"] ?? "A1");
  const rowIndex = range.e.r + 1;
  columns.forEach((col, index) => {
    const value = totals[col.header] ?? (index === 0 ? "Total" : "");
    const addr = XLSX.utils.encode_cell({ r: rowIndex, c: index });
    sheet[addr] = { t: typeof value === "number" ? "n" : "s", v: value };
  });
  sheet["!ref"] = XLSX.utils.encode_range({
    s: range.s,
    e: { r: rowIndex, c: range.e.c },
  });
}

export function buildReportWorkbook(input: ExcelWorkbookInput): XLSX.WorkBook {
  const workbook = XLSX.utils.book_new();
  if (input.context) {
    XLSX.utils.book_append_sheet(
      workbook,
      buildMetadataSheet(input.context, input.title),
      "Metadata"
    );
  }
  for (const dataSheet of input.sheets) {
    const sheet = rowsToSheet(dataSheet.columns, dataSheet.rows);
    if (dataSheet.totals) {
      appendTotalsRow(sheet, dataSheet.columns, dataSheet.totals);
    }
    const safeName = dataSheet.name.slice(0, 31).replace(/[\\/?*[\]]/g, "");
    XLSX.utils.book_append_sheet(workbook, sheet, safeName || "Data");
  }
  return workbook;
}

export function workbookToBase64(workbook: XLSX.WorkBook): string {
  return XLSX.write(workbook, { bookType: "xlsx", type: "base64" });
}

export function workbookToBuffer(workbook: XLSX.WorkBook): Buffer {
  return Buffer.from(XLSX.write(workbook, { bookType: "xlsx", type: "array" }));
}

export function downloadWorkbookClient(workbook: XLSX.WorkBook, fileName: string): void {
  const name = fileName.endsWith(".xlsx") ? fileName : `${fileName}.xlsx`;
  XLSX.writeFile(workbook, name);
}

export function downloadBase64Excel(base64: string, fileName: string): void {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  const blob = new Blob([bytes], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName.endsWith(".xlsx") ? fileName : `${fileName}.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
}

export function bilingualSheetName(en: string, ar?: string): string {
  if (!ar) return en.slice(0, 31);
  return `${en}`.slice(0, 31);
}
