"use client";

import { formatDateTime } from "@/lib/format";
import { useTranslation } from "@/lib/i18n/use-translation";

interface ReportFooterProps {
  generatedBy: string;
  generatedAt: string;
  filterSummary?: string;
}

export function ReportFooter({ generatedBy, generatedAt, filterSummary }: ReportFooterProps) {
  const { t } = useTranslation();
  return (
    <footer className="mt-8 border-t pt-4 text-xs text-muted-foreground">
      <div className="flex flex-wrap justify-between gap-2">
        <span>
          {t("Generated by")}: {generatedBy} · {formatDateTime(generatedAt)}
        </span>
        {filterSummary ? (
          <span>
            {t("Filters")}: {filterSummary}
          </span>
        ) : null}
      </div>
    </footer>
  );
}
